CREATE DATABASE IF NOT EXISTS CLASS_DATABASE;
USE CLASS_DATABASE;
DROP TABLE IF EXISTS OrderDetails;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
    UserID INT,
    Username VARCHAR(50),
    Email VARCHAR(100),
    UserStatus VARCHAR(20),
    CreatedAt DATETIME
);
CREATE TABLE Categories (
    CategoryID INT,
    CategoryName VARCHAR(50),
    Description TEXT
);
CREATE TABLE Products (
    ProductID INT,
    ProductName VARCHAR(100),
    Price DECIMAL(10, 2),
    StockQuantity INT,
    CategoryID INT
);

CREATE TABLE Orders (
    OrderID INT,
    OrderDate DATETIME,
    TotalAmount DECIMAL(10, 2),
    UserID INT
);
ALTER TABLE Users ADD PRIMARY KEY (UserID);
ALTER TABLE Categories ADD PRIMARY KEY (CategoryID);
ALTER TABLE Products ADD PRIMARY KEY (ProductID);
ALTER TABLE Orders ADD PRIMARY KEY (OrderID);
ALTER TABLE Users 
    MODIFY Username VARCHAR(50) NOT NULL UNIQUE,
    MODIFY Email VARCHAR(100) NOT NULL;
ALTER TABLE Users MODIFY UserStatus VARCHAR(20) DEFAULT 'Active';
ALTER TABLE Users MODIFY CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Orders MODIFY OrderDate DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Products ADD CONSTRAINT CHK_Price CHECK (Price > 0);
ALTER TABLE Products ADD CONSTRAINT CHK_Stock CHECK (StockQuantity >= 0);
ALTER TABLE Products 
    ADD CONSTRAINT FK_Category 
    FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID);
ALTER TABLE Orders 
    ADD CONSTRAINT FK_UserOrder 
    FOREIGN KEY (UserID) REFERENCES Users(UserID) 
    ON DELETE CASCADE;
SHOW TABLES;
DESCRIBE Users;
DESCRIBE Products;
SHOW INDEX FROM Users;